
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OsinavPortal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sinav
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sinav()
    {

        this.Soru = new HashSet<Soru>();

    }


    public int sinavId { get; set; }

    public string sinavAdi { get; set; }

    public int sinavSuresi { get; set; }

    public int sinavDersId { get; set; }



    public virtual Ders Ders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Soru> Soru { get; set; }

}

}
