
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OsinavPortal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Uye
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Uye()
    {

        this.UyeCevap = new HashSet<UyeCevap>();

        this.UyeDers = new HashSet<UyeDers>();

    }


    public int uyeId { get; set; }

    public string adsoyad { get; set; }

    public int admin { get; set; }

    public string mail { get; set; }

    public string parola { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UyeCevap> UyeCevap { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UyeDers> UyeDers { get; set; }

}

}
