
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace OsinavPortal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UyeCevap
{

    public int uyeCevapId { get; set; }

    public int uId { get; set; }

    public int secId { get; set; }



    public virtual Secenek Secenek { get; set; }

    public virtual Uye Uye { get; set; }

}

}
